In [1]:
import os
os.getcwd()

'C:\\Users\\saras\\Documents\\Y4\\HonsProject\\notebooks'

In [3]:
import pandas as pd
import json
from sqlalchemy import create_engine

engine = create_engine("sqlite:///../data/names_results1.db")
df = pd.read_sql("SELECT * FROM names", engine)
df["full_countries_distribution"] = df["full_countries_distribution"].apply(json.loads)

df.head()

,name,full_countries_distribution,top_country,top_country_prob,strong_top_country,agreement_score,n_models_used,name_script,name_latin,eth_EastAsian,...,eth_Hispanic,eth_Italian,eth_Nordic,ethnicolr_race,langdetect_lang,langdetect_prob,hunspell_orig_known,hunspell_latin_known,pysc_orig_known,pysc_latin_known
0,A A,"{'Afghanistan': None, 'Albania': None, 'Algeri...",Bangladesh,0.329,0,NaN,0,Latin,A A,0.106898,...,0.070977,0.063327,0.154168,"GreaterAfrican,Muslim",hu,1.0000,0,0,0,0
1,A A A,"{'Afghanistan': None, 'Albania': None, 'Algeri...",Bangladesh,0.714,1,NaN,0,Latin,A A A,0.230757,...,0.053853,0.046734,0.116572,"Asian,GreaterEastAsian,EastAsian",hu,1.0000,0,0,0,0
2,A A Ron,"{'Afghanistan': None, 'Albania': None, 'Algeri...",United States,0.615,0,NaN,0,Latin,A A Ron,0.670941,...,0.016496,0.011205,0.015815,"Asian,GreaterEastAsian,EastAsian",hu,1.0000,0,0,0,0
3,A Abdiel,"{'Afghanistan': None, 'Albania': None, 'Algeri...",Panama,1.000,1,NaN,0,Latin,A Abdiel,0.010752,...,0.025052,0.021789,0.004987,"GreaterAfrican,Africans",de,0.7143,0,0,0,0
4,A Abera,"{'Afghanistan': None, 'Albania': None, 'Algeri...",Ethiopia,1.000,1,NaN,0,Latin,A Abera,0.044627,...,0.037988,0.097774,0.052131,"GreaterAfrican,Muslim",hu,0.7143,0,0,0,0

In [3]:
df2 = pd.read_sql("select count(*) from names where strong_top_country", engine)
df2.head()

   count(*)
0    339711

In [5]:
pd.read_sql("SELECT * FROM names WHERE name_script != 'Latin'", engine).head()

,name,full_countries_distribution,top_country,top_country_prob,strong_top_country,agreement_score,n_models_used,name_script,name_latin,eth_EastAsian,...,eth_Hispanic,eth_Italian,eth_Nordic,ethnicolr_race,langdetect_lang,langdetect_prob,hunspell_orig_known,hunspell_latin_known,pysc_orig_known,pysc_latin_known
0,[[,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Morocco,0.881,1,NaN,0,Other,[[,NaN,...,NaN,NaN,NaN,None,None,NaN,0,0,0,0
1,Άβα,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Greece,1.000,1,NaN,0,Greek,Ava,0.045876,...,0.033241,0.054120,0.007559,"GreaterAfrican,Muslim",el,1.0,0,1,0,0
2,Άγγελα,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Cyprus,1.000,1,NaN,0,Greek,Aggela,0.020201,...,0.025209,0.055258,0.396450,"GreaterEuropean,WestEuropean,Nordic",el,1.0,0,0,0,0
3,Άγγελος,"{""Afghanistan"": null, ""Albania"": 0.008, ""Alger...",Greece,0.912,1,NaN,0,Greek,Aggelos,0.002790,...,0.094509,0.262897,0.042508,"GreaterEuropean,WestEuropean,Italian",el,1.0,0,0,0,0
4,Άγης,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Greece,0.800,1,NaN,0,Greek,Agis,0.063292,...,0.038788,0.102621,0.128907,"GreaterAfrican,Muslim",el,1.0,0,0,0,0

In [7]:
pd.read_sql("SELECT * FROM names WHERE name_script = 'Other'", engine)

,name,full_countries_distribution,top_country,top_country_prob,strong_top_country,agreement_score,n_models_used,name_script,name_latin,eth_EastAsian,...,eth_Hispanic,eth_Italian,eth_Nordic,ethnicolr_race,langdetect_lang,langdetect_prob,hunspell_orig_known,hunspell_latin_known,pysc_orig_known,pysc_latin_known
0,[[,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Morocco,0.881,1,None,0,Other,[[,None,...,None,None,None,None,None,None,0,0,0,0

In [4]:
mask = df["name"].str.match(r"^[A-Za-z]?\s[A-Za-z]?$")
filtered = df[mask]
len(filtered)

180

In [6]:
filtered

,name,full_countries_distribution,top_country,top_country_prob,strong_top_country,agreement_score,n_models_used,name_script,name_latin,eth_EastAsian,...,eth_Hispanic,eth_Italian,eth_Nordic,ethnicolr_race,langdetect_lang,langdetect_prob,hunspell_orig_known,hunspell_latin_known,pysc_orig_known,pysc_latin_known
0,A A,"{'Afghanistan': None, 'Albania': None, 'Algeri...",Bangladesh,0.329,0,NaN,0,Latin,A A,0.106898,...,0.070977,0.063327,0.154168,"GreaterAfrican,Muslim",hu,1.0000,0,0,0,0
13,A B,"{'Afghanistan': None, 'Albania': None, 'Algeri...",Bangladesh,0.366,0,NaN,0,Latin,A B,0.108018,...,0.054446,0.047924,0.149725,"GreaterEuropean,EastEuropean",hu,1.0000,0,0,0,0
19,A C,"{'Afghanistan': None, 'Albania': None, 'Algeri...",India,0.179,0,NaN,0,Latin,A C,0.197476,...,0.068748,0.046946,0.115233,"Asian,GreaterEastAsian,EastAsian",hu,1.0000,0,0,0,0
25,A D,"{'Afghanistan': None, 'Albania': None, 'Algeri...",India,0.344,0,NaN,0,Latin,A D,0.102077,...,0.072321,0.147354,0.039781,"GreaterEuropean,WestEuropean,Italian",hu,1.0000,0,0,0,0
33,A F,"{'Afghanistan': None, 'Albania': None, 'Algeri...",Bangladesh,0.485,0,NaN,0,Latin,A F,0.160630,...,0.062641,0.046074,0.107373,"Asian,GreaterEastAsian,EastAsian",hu,1.0000,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554106,W F,"{'Afghanistan': None, 'Albania': None, 'Algeri...",Morocco,0.567,0,NaN,0,Latin,W F,0.160630,...,0.062641,0.046074,0.107373,"Asian,GreaterEastAsian,EastAsian",pl,1.0000,0,0,0,0
565225,Y B,"{'Afghanistan': None, 'Albania': None, 'Algeri...",Morocco,0.933,1,NaN,0,Latin,Y B,0.108018,...,0.054446,0.047924,0.149725,"GreaterEuropean,EastEuropean",cy,1.0000,0,0,0,0
578065,Z K,"{'Afghanistan': None, 'Albania': None, 'Algeri...",Morocco,0.922,1,NaN,0,Latin,Z K,0.109876,...,0.056153,0.066596,0.141777,"GreaterEuropean,WestEuropean,Germanic",sl,0.7143,0,0,0,0
578067,Z M,"{'Afghanistan': None, 'Albania': None, 'Algeri...",Morocco,0.890,1,NaN,0,Latin,Z M,0.094004,...,0.057930,0.059076,0.121163,"GreaterEuropean,EastEuropean",sl,1.0000,0,0,0,0
578074,Z Z,"{'Afghanistan': None, 'Albania': None, 'Algeri...",Morocco,0.884,1,NaN,0,Latin,Z Z,0.115015,...,0.023570,0.023561,0.019317,"GreaterAfrican,Muslim",sl,1.0000,0,0,0,0

In [7]:
pd.read_sql("SELECT * FROM names WHERE langdetect_prob != 1.0", engine)

,name,full_countries_distribution,top_country,top_country_prob,strong_top_country,agreement_score,n_models_used,name_script,name_latin,eth_EastAsian,...,eth_Hispanic,eth_Italian,eth_Nordic,ethnicolr_race,langdetect_lang,langdetect_prob,hunspell_orig_known,hunspell_latin_known,pysc_orig_known,pysc_latin_known
0,A Abdiel,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Panama,1.000,1,NaN,0,Latin,A Abdiel,0.010752,...,0.025052,0.021789,0.004987,"GreaterAfrican,Africans",de,0.7143,0,0,0,0
1,A Abera,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Ethiopia,1.000,1,NaN,0,Latin,A Abera,0.044627,...,0.037988,0.097774,0.052131,"GreaterAfrican,Muslim",hu,0.7143,0,0,0,0
2,A Alilliom,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Hungary,1.000,1,NaN,0,Latin,A Alilliom,0.009058,...,0.084076,0.070937,0.012979,"GreaterEuropean,British",pt,0.8571,0,0,0,0
3,A Amila,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Slovenia,1.000,1,NaN,0,Latin,A Amila,0.013497,...,0.078863,0.020140,0.068330,"Asian,IndianSubContinent",tl,0.8571,0,0,0,0
4,A Amson,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Georgia,1.000,1,NaN,0,Latin,A Amson,0.139072,...,0.025235,0.046247,0.019663,"GreaterEuropean,British",hu,0.5714,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239827,ﻣﺤﻤﺪاﻟﻠﻪ,"{""Afghanistan"": 1.0, ""Albania"": null, ""Algeria...",Afghanistan,1.000,1,NaN,0,Arabic,mhmdllh,0.132382,...,0.005686,0.003065,0.272708,"GreaterEuropean,WestEuropean,Nordic",ar,0.9994,0,0,0,0
239828,ﻧﺼﻴﺮاﺣﻤﺪ,"{""Afghanistan"": 1.0, ""Albania"": null, ""Algeria...",Afghanistan,1.000,1,NaN,0,Arabic,nsyrhmd,0.005772,...,0.002221,0.000666,0.008716,"GreaterAfrican,Muslim",ar,0.9994,0,0,0,0
239829,ﻧﻮﺭاﻟﺪﻳﻦ,"{""Afghanistan"": 1.0, ""Albania"": null, ""Algeria...",Afghanistan,1.000,1,NaN,0,Arabic,nwrldyn,0.060282,...,0.016827,0.003015,0.021506,"GreaterEuropean,British",ar,0.9994,0,0,0,0
239830,ﻧﻮﺭاﻟﻠﻪ,"{""Afghanistan"": 0.909, ""Albania"": null, ""Alger...",Afghanistan,0.909,1,NaN,0,Arabic,nwrllh,0.116982,...,0.007430,0.001125,0.281251,"GreaterEuropean,WestEuropean,Nordic",ar,0.9994,0,0,0,0
239831,ﻫﺪاﻳﺖ,"{""Afghanistan"": 0.75, ""Albania"": null, ""Algeri...",Afghanistan,0.750,1,NaN,0,Arabic,hdyt,0.109544,...,0.073102,0.125194,0.029136,"GreaterEuropean,WestEuropean,Italian",ar,0.9994,0,0,0,0

In [11]:
engine = create_engine("sqlite:///../data/names2.db")
df2 = pd.read_sql("SELECT * FROM names", engine)
len(df2)

engine = create_engine("sqlite:///../data/names.db")
df = pd.read_sql("SELECT * FROM names", engine)
len(df)

727545

In [14]:
# Count number of parts when splitting by space
mask = df["name"].str.split().str.len() > 2

# Filter
multi_part_names = df[mask]
len(multi_part_names)

7510

In [20]:
engine = create_engine("sqlite:///../data/names_results1.db")
pd.read_sql("SELECT * FROM names WHERE top_country = 'Israel' AND top_country_prob >= 0.4", engine).head()

,name,full_countries_distribution,top_country,top_country_prob,strong_top_country,agreement_score,n_models_used,name_script,name_latin,eth_EastAsian,...,eth_Hispanic,eth_Italian,eth_Nordic,ethnicolr_race,langdetect_lang,langdetect_prob,hunspell_orig_known,hunspell_latin_known,pysc_orig_known,pysc_latin_known
0,Achiad,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Israel,0.750,1,NaN,0,Latin,Achiad,0.074101,...,0.026056,0.018933,0.059288,"Asian,IndianSubContinent",cy,1.0000,0,0,0,0
1,Achikam,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Israel,0.591,0,NaN,0,Latin,Achikam,0.092329,...,0.009883,0.009299,0.029020,"Asian,GreaterEastAsian,Japanese",sw,1.0000,0,0,0,0
2,Achinoam,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Israel,0.723,1,NaN,0,Latin,Achinoam,0.089508,...,0.009503,0.035204,0.009385,"Asian,GreaterEastAsian,Japanese",en,1.0000,0,0,0,0
3,Achiya,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Israel,0.415,0,NaN,0,Latin,Achiya,0.323621,...,0.001948,0.001445,0.001732,"Asian,GreaterEastAsian,Japanese",sw,0.8571,0,0,0,0
4,Achva,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Israel,0.786,1,NaN,0,Latin,Achva,0.111833,...,0.088419,0.025983,0.086272,"GreaterEuropean,EastEuropean",sk,1.0000,0,0,0,0